name: auto deploy # workflow name

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: auto deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Aliyun OSS
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hongkong.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: Deploy to  Aliyun OSS
      run: ossutil cp -rf ./test/ oss://xaoxuu-hk-assets/timeline/
